export interface dataLibro {
  titulo?: string,
  autor?: string,
  editorial?: string,
  fechaPublicacion?: string,
  descripcion?: string,
  numeroPaginas?: string,
  generos?: Array<string>,
  valoracion?: string,
  imagen?: string,
  precio?: string,
  idioma?: string,
  linkDeVenta?: string,
  linkPreviewLibro?: string,
}
